# fly.toml app configuration file generated for watch-out on 2024-02-19T04:24:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'watch-out'
primary_region = 'sin'

[build]

[deploy]
  # release_command = 'sh ./release.sh'

[env]
  CLIENT_URL = 'https://watch-outt.netlify.app'
  DATABASE = 'watch-out'
  DIALECT = 'postgres'
  HOST = 'watch-out-db.internal'
  NODE_ENV = 'production'
  PASSWORD = 'iUnEXHYvLflxJTE'
  PORT = '3000'
  USERNAME = 'postgres'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

[[vm]]
  size = 'shared-cpu-1x'
